apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-recomm
  labels:
    app: fashion-recomm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion-recomm
  template:
    metadata:
      labels:
        app: fashion-recomm
    spec:
      containers:
      - name: fashion-recomm
        image: gcr.io/fashion-cicd-project-463004/fashion-recomm:latest
        ports:
        - containerPort: 80
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi